export interface Category {
  id: string;
  name: string;
  icon: string;
  questionCount: number;
}

export const CATEGORIES: Category[] = [
  { id: "beliefs", name: "Beliefs", icon: "💡", questionCount: 15 },
  { id: "writing-mechanics", name: "Writing Mechanics", icon: "✏️", questionCount: 20 },
  { id: "aesthetic", name: "Aesthetic", icon: "🎨", questionCount: 15 },
  { id: "voice", name: "Tone", icon: "🎙️", questionCount: 15 },
  { id: "structure", name: "Structure", icon: "🏗️", questionCount: 15 },
  { id: "hard-nos", name: "Hard Nos", icon: "🚫", questionCount: 10 },
  { id: "red-flags", name: "Red Flags", icon: "🚩", questionCount: 10 },
];

export const INITIAL_QUESTIONS: Record<string, string[]> = {
  beliefs: [
    "What inspired you to start documenting your process?",
    "If you had to describe your writing's primary goal in one word—clarity, character, or efficiency—which would it be, and why?",
    "What's the most controversial opinion you hold about writing that most people would disagree with?",
    "Do you believe writing should primarily serve the reader or the writer? Why?",
    "What's a widely accepted writing 'rule' you deliberately break?",
    "How do you distinguish between your authentic voice and a voice you've been conditioned to use?",
    "What role does vulnerability play in your writing?",
    "Do you write to persuade, to clarify, or to provoke? When does that shift?",
    "What's the difference between honesty and transparency in writing?",
    "When you read something brilliant, what specifically makes it brilliant to you?",
    "Do you think writing quality is objective or purely subjective? Where do you draw the line?",
    "What's the most overrated quality in writing?",
    "Is there a writer whose work you admire but whose approach you'd never adopt?",
    "How do you handle writing about topics where you're uncertain?",
    "What would make you stop writing entirely?",
  ],
  "writing-mechanics": [
    "How long are your typical sentences? Do you favor short punches or long, layered constructions?",
    "What's your relationship with semicolons?",
    "How do you approach paragraph breaks — by logic, rhythm, or visual balance?",
    "Do you use em dashes, parentheses, or commas for asides? Why that one?",
    "How do you handle transitions between ideas?",
    "What's your approach to opening lines?",
    "Do you prefer active or passive voice? Are there exceptions?",
    "How do you handle jargon when writing for mixed audiences?",
    "What role does repetition play in your writing?",
    "How do you decide when to use a list versus prose?",
    "What's your editing process — do you cut, restructure, or polish?",
    "How many drafts does your typical piece go through?",
    "Do you write linearly or jump around?",
    "How do you handle quotes and attribution?",
    "What's your approach to analogies and metaphors — frequent, rare, or strategic?",
    "How do you pace your arguments?",
    "Do you use hedging language ('perhaps', 'might', 'arguably') and why?",
    "How do you handle numerical data in prose?",
    "What's your stance on sentence fragments as a stylistic choice?",
    "How do you decide where to end a piece?",
  ],
  aesthetic: [
    "If your writing were a room, what would it look like?",
    "What's the visual texture of your prose — clean and sparse, or dense and layered?",
    "Do you care about how your writing looks on the page?",
    "What's a word you use too often and can't stop?",
    "What's a word or phrase you'd never use?",
    "How do you feel about exclamation marks?",
    "Is humor a tool in your writing or a liability?",
    "How do you handle profanity in your work?",
    "What's your approach to naming things — titles, headers, sections?",
    "Do you prefer precision or suggestion?",
    "How important is rhythm in your sentences?",
    "What's an aesthetic choice another writer makes that you find beautiful but wouldn't use?",
    "How do you handle abstraction versus concrete detail?",
    "What's the visual rhythm of your paragraphs?",
    "Do you write for the ear or the eye?",
  ],
  voice: [
    "If your writing had a temperature, what would it be?",
    "Are you warm or cool with your reader?",
    "How do you handle authority — do you assert, suggest, or question?",
    "What persona emerges when you write under pressure?",
    "Do you address the reader directly?",
    "How personal do you get in professional writing?",
    "What's the emotional range of your typical piece?",
    "How do you signal sarcasm or irony in text?",
    "What's the difference between your speaking voice and your writing voice?",
    "How do you handle disagreement in writing?",
    "Do you have a writing tic that you're aware of?",
    "How do you establish credibility without being pedantic?",
    "What's the energy level of your prose?",
    "How do you handle endings — do you conclude, trail off, or surprise?",
    "If a stranger read your writing without knowing you, what would they assume about you?",
  ],
  structure: [
    "How do you typically structure a piece — chronologically, thematically, or argumentatively?",
    "What role do headers and subheaders play in your work?",
    "How long are your typical pieces?",
    "Do you prefer flat structures or nested hierarchies?",
    "How do you handle context-setting at the beginning of a piece?",
    "What's your approach to conclusions?",
    "How do you structure arguments with multiple supporting points?",
    "Do you front-load your main point or build toward it?",
    "How do you handle tangents?",
    "What's your approach to footnotes or asides?",
    "How do you decide what to cut versus keep?",
    "Do you outline before writing or discover structure as you go?",
    "How do you handle pieces that need to cover multiple distinct topics?",
    "What's your relationship with white space?",
    "How do you structure a piece differently when you're uncertain about your conclusion?",
  ],
  "hard-nos": [
    "What's a writing technique that immediately makes you stop reading?",
    "What cliché do you refuse to use, even ironically?",
    "What formatting choice is an absolute dealbreaker?",
    "What tone is completely off-limits for you?",
    "What kind of opening line would you never write?",
    "What's a structural choice you consider lazy?",
    "What rhetorical device do you find manipulative?",
    "What writing advice do you actively reject?",
    "What's something you see in published writing that makes you cringe?",
    "What's a compliment about your writing that would actually offend you?",
  ],
  "red-flags": [
    "How can you tell when someone is imitating your voice badly?",
    "What would an AI most likely get wrong about your writing?",
    "What's the subtlest thing that distinguishes your writing from a good imitation?",
    "If you read an AI-generated version of your writing, what would tip you off immediately?",
    "What pattern would an AI likely overuse if it had your profile?",
    "What's the most common way people mischaracterize your writing style?",
    "What would you add to an AI prompt to prevent it from making your writing too polished?",
    "What's the difference between your 'first draft voice' and your 'published voice'?",
    "What element of your writing is most resistant to being captured in a profile?",
    "What would you tell an AI to never do when writing as you?",
  ],
};

export const TOTAL_QUESTIONS = CATEGORIES.reduce((sum, c) => sum + c.questionCount, 0);
